# Build using a Dockerfile (embedded) simply adding the jar to the Fuse image where it expects it
# oc start-build -F fuse7-hello-dockerfile-binary --from-dir=./target
apiVersion: v1
kind: ImageStream
metadata:
  name: fuse7-hello-dockerfile-binary
  labels:
    app: fuse7-hello
spec:
  lookupPolicy:
    local: true
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: fuse7-hello-dockerfile-binary
  labels:
    app: fuse7-hello
spec:
  output:
    to:
      kind: ImageStreamTag
      name: "fuse7-hello-dockerfile-binary:latest"
  source:
    type: Binary
    binary: {}
    dockerfile: |-
      FROM overwritten-from-strategy-field
      COPY *.jar /deployments/
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/fuse7/fuse-java-openshift:1.7